---
title: "Pilot A analysis"
format: html
editor: visual
---


```{r}
library(tidyverse)
library(pwr)        
library(emmeans)


files <- c(
  "4qcemy4k.csv",
  "bqlvmxzf.csv"
)

# Read and combine all files from ../stims
data.raw <- files %>%
  set_names() %>% 
  map_dfr(
    ~ read_csv(file.path("../data", .x)),
    .id = "source_file"
  )

stims.raw <- read.csv("../stims/kim_et_al_2024_stimuli_1.csv") # stimulus data direct as csv

# Remove filler and practice entries
# Focus on only target word for now (i.e. deepest NP in clause)
data <- data.raw %>%
  left_join(stims.raw %>% select(item_id, target_word), by = join_by(item_id)) %>%
  mutate(rt = as.numeric(rt),
         whword = ifelse(condition == 'a', 'object who', 
                         ifelse(condition == 'b', 'how',
                                ifelse(condition == 'c', 'that',
                                       'why')))) %>% # condition = wh-word used in sentence
  filter(item_type != 'filler' & item_type != 'practice') %>%
  mutate(is_target_word = (target_word == word)) %>% # select only deepest embedded NP
  filter(is_target_word)
  


write.csv(df.raw, "../data/pilot_a_data.csv")
```

```{r}
# Compute mean reaction time per condition
agr <- data %>%
  mutate(rt_log = log(rt)) %>%
  group_by(whword) %>%
  summarise(n = n(), se = sd(rt_log) / sqrt(n()), y = mean(rt_log)) %>%
  mutate(
    whword = factor(
      whword,
      levels = c("object who", "how", "that", "why")
    ) )# Order whword elements to be object who, how, that, why

agr


ggplot(agr, aes(x = whword, y = y, fill = whword)) +
  geom_bar(stat = "identity", width = 0.6, color = "black", linewidth = 1) +
  geom_errorbar(aes(ymin = y - se, ymax = y + se ),   
                width = 0.08,   linewidth = 1 ) +
  scale_fill_manual(values = c("object who" = "blue",
                               "how" = "darkred",
                               "that" = "green",
                               "why" = "purple")) +
  coord_cartesian(ylim = c(5, 5.6)) +
  labs(x = "wh-types", y = "Reaction time (log ms)") +
  ggtitle("Reading times at the most deeply embedded N") +
  theme_classic(base_size = 18) +
  theme(
    legend.position = "none",
    axis.text.x = element_text(
      angle = 20,
      hjust = 1
    ),
    axis.line = element_line(linewidth = 1),
    axis.ticks = element_line(linewidth = 1)
  )
```

