---
title: "Power B analysis"
format: html
editor: visual
---

```{r}
library(tidyverse)
library(pwr)        
library(emmeans)


files <- c(
  c(
    "0j17p08k.csv",
    "1dg2qhj2b3.csv",
    "1e17ytgq.csv",
    "1fqrd6qr.csv",
    "1lmu0rmy.csv",
    "1orqqvyp.csv",
    "1qr6nnt1.csv",
    "1sftbbwm.csv",
    "2bomnjjb.csv",
    "2ea7uxyc.csv",
    "2ewef3gm.csv",
    "2odgntx7.csv",
    "3e3v39z8.csv",
    "3jtr11xk.csv",
    "3og97j2k.csv",
    "3ut1qsdd.csv",
    "4gjn1seg.csv",
    "4qcemy4k.csv",
    "4yxop4r3.csv",
    "5lqc6nvcre.csv",
    "5vrdpq0t.csv",
    "7f2wtp1j.csv",
    "7lhlpfus.csv",
    "7mza4pym.csv",
    "9kd8a7eb.csv",
    "9nvsempv62.csv",
    "20frs6ol.csv",
    "31by1doq.csv",
    "91mfkpae.csv",
    "120ypmwg.csv",
    "352jd0sb.csv",
    "970gbe0a.csv",
    "a7afpb9w.csv",
    "adbunmf0.csv",
    "ajl3gqra.csv",
    "bn7akg4o.csv",
    "bo3a253d.csv",
    "bqlvmxzf.csv",
    "c1m9yfql.csv",
    "cktudb9s.csv",
    "dsfc282a.csv",
    "e34duc56.csv",
    "el2hvftl.csv",
    "gfzoatpu.csv",
    "h8nlnku2.csv",
    "h6253x9m.csv",
    "hb3mv8ph.csv",
    "hb4brkxq.csv",
    "hs2xklzn.csv",
    "hwsqhjot.csv",
    "jrj7xzuf.csv",
    "k2b5yzkl.csv",
    "k8rnkquz.csv",
    "kl8k8j1y.csv",
    "lta397lq.csv",
    "luzwjk24.csv",
    "lwvpwcq0.csv",
    "m1eabfx1.csv",
    "n8adea4h.csv",
    "na6hh0ua.csv",
    "nflshhgq.csv",
    "o92u56uh.csv",
    "ogyjt8yg.csv",
    "ojv4jxxa.csv",
    "olol1tte.csv",
    "orybxbxu.csv",
    "p3taub1f.csv",
    "pco9vqna.csv",
    "pm5zycnt.csv",
    "ppt63ukd.csv",
    "q330tno2.csv",
    "qbwjdear.csv",
    "qfm8ks37.csv",
    "qgzx1bfu.csv",
    "r0pm70sc.csv",
    "r1o8o6o4.csv",
    "repvu995.csv",
    "rxur173z.csv",
    "s3j977x7.csv",
    "szh4zjou.csv",
    "tf6nb9bm.csv",
    "tpt94g2b.csv",
    "tw3k60gy.csv",
    "txdtrb48.csv",
    "u0pme1hk.csv",
    "u1s85lkk.csv",
    "u2fs8oqd.csv",
    "ucyeq6mc.csv",
    "uu3k1546.csv",
    "vg74l3ea.csv",
    "vgp86ou0.csv",
    "vp4hn41a.csv",
    "w3yqa2f3.csv",
    "xthmgyn8.csv",
    "y14x4t45.csv",
    "yu3vjzn3.csv",
    "z25ltc96.csv"
  )
)

# Read and combine all files from ../stims
data.raw <- files %>%
  set_names() %>% 
  map_dfr(
    ~ read_csv(file.path("../data/pilotb", .x)) %>% mutate(rt = as.numeric(rt)),
    .id = "source_file"
  )

stims.raw <- read.csv("../stims/stims_abridged_all_info.csv") # stimulus data direct as csv

# Remove filler and practice entries
# Focus on only target word for now (i.e. deepest NP in clause)
data <- data.raw %>%
  left_join(stims.raw %>% select(item_id, target_word), multiple = "first", by = join_by(item_id)) %>%
  mutate(rt = as.numeric(rt),
         log_rt = log(rt),
         whword = ifelse(condition == 'a', 'object who', 
                         ifelse(condition == 'b', 'how',
                                ifelse(condition == 'c', 'that',
                                       'why')))) %>% # condition = wh-word used in sentence
  filter(item_type != 'filler' & item_type != 'practice') %>%
  mutate(is_target_word = (target_word == word)) %>% # select only deepest embedded NP
  filter(is_target_word)
  
data <- data %>% select(source_file, participant_id, trial_type, trial_index, rt, log_rt, condition, item_id, word, word_index, too_fast, target_word, whword, is_target_word)

write.csv(data, "../data/pilot_b_data.csv")
```

```{r}
# Compute mean reaction time per condition
agr <- data %>%
  group_by(whword) %>%
  summarise(n = n(), se = sd(log_rt) / sqrt(n()), y = mean(log_rt)) %>%
  mutate(
    whword = factor(
      whword,
      levels = c("object who", "how", "that", "why")
    ) )# Order whword elements to be object who, how, that, why

agr


ggplot(agr, aes(x = whword, y = y, fill = whword)) +
  geom_bar(stat = "identity", width = 0.6, color = "black", linewidth = 1) +
  geom_errorbar(aes(ymin = y - se, ymax = y + se ),   
                width = 0.08,   linewidth = 1 ) +
  scale_fill_manual(values = c("object who" = "blue",
                               "how" = "darkred",
                               "that" = "green",
                               "why" = "purple")) +
  coord_cartesian(ylim = c(5, 5.6)) +
  labs(x = "wh-types", y = "Reaction time (log ms)") +
  ggtitle("Reading times at the most deeply embedded N") +
  theme_classic(base_size = 18) +
  theme(
    legend.position = "none",
    axis.text.x = element_text(
      angle = 20,
      hjust = 1
    ),
    axis.line = element_line(linewidth = 1),
    axis.ticks = element_line(linewidth = 1)
  )
```

```{r}
library(lme4)
library(lmerTest)

# Fit mixed-effects regression
model <- lmer(
  log_rt ~ whword + 
    (1 | participant_id) + 
    (1 | item_id),
  data = data
)

# View results
summary(model)
```
