const experimentStimuli = [
  {
    "no": 97,
    "exp_id": "1b_2a",
    "condition": "a",
    "item_type": 1,
    "item_id": "1b_2a-1",
    "stimulus": "The aide noticed who the generous teacher that the exemplary dean employed graciously and happily gave the prize to.",
    "target_word": "dean",
    "question": "Did the teacher give a prize to the student?",
    "correct_answer": "f"
  },
  {
    "no": 98,
    "exp_id": "1b_2a",
    "condition": "b",
    "item_type": 1,
    "item_id": "1b_2a-1",
    "stimulus": "The aide noticed how the generous teacher that the exemplary dean employed graciously and happily gave the prize to the student.",
    "target_word": "dean",
    "question": "Did the teacher give a prize to the student?",
    "correct_answer": "f"
  },
  {
    "no": 99,
    "exp_id": "1b_2a",
    "condition": "c",
    "item_type": 1,
    "item_id": "1b_2a-1",
    "stimulus": "The aide noticed that the generous teacher that the exemplary dean employed graciously and happily gave the prize to the student.",
    "target_word": "dean",
    "question": "Did the teacher give a prize to the student?",
    "correct_answer": "f"
  },
  {
    "no": 100,
    "exp_id": "1b_2a",
    "condition": "d",
    "item_type": 1,
    "item_id": "1b_2a-1",
    "stimulus": "The aide noticed why the generous teacher that the exemplary dean employed graciously and happily gave the prize to the student.",
    "target_word": "dean",
    "question": "Did the teacher give a prize to the student?",
    "correct_answer": "f"
  },
  {
    "no": 101,
    "exp_id": "1b_2a",
    "condition": "a",
    "item_type": 2,
    "item_id": "1b_2a-2",
    "stimulus": "The student noticed who the tough coach that the popular athlete admired obviously and unnecessarily paid more attention to.",
    "target_word": "athlete",
    "question": "Did the coach ignore the quarterback?",
    "correct_answer": "j"
  },
  {
    "no": 102,
    "exp_id": "1b_2a",
    "condition": "b",
    "item_type": 2,
    "item_id": "1b_2a-2",
    "stimulus": "The student noticed how the tough coach that the popular athlete admired obviously and unnecessarily paid more attention to the quarterback.",
    "target_word": "athlete",
    "question": "Did the coach ignore the quarterback?",
    "correct_answer": "j"
  },
  {
    "no": 103,
    "exp_id": "1b_2a",
    "condition": "c",
    "item_type": 2,
    "item_id": "1b_2a-2",
    "stimulus": "The student noticed that the tough coach that the popular athlete admired obviously and unnecessarily paid more attention to the quarterback.",
    "target_word": "athlete",
    "question": "Did the coach ignore the quarterback?",
    "correct_answer": "j"
  },
  {
    "no": 104,
    "exp_id": "1b_2a",
    "condition": "d",
    "item_type": 2,
    "item_id": "1b_2a-2",
    "stimulus": "The student noticed why the tough coach that the popular athlete admired obviously and unnecessarily paid more attention to the quarterback.",
    "target_word": "athlete",
    "question": "Did the coach ignore the quarterback?",
    "correct_answer": "j"
  },
  {
    "no": 105,
    "exp_id": "1b_2a",
    "condition": "a",
    "item_type": 3,
    "item_id": "1b_2a-3",
    "stimulus": "The pilot noticed who the pretty attendant that the famous airline hired kindly and thoughtfully gave extra attention to.",
    "target_word": "airline",
    "question": "Did the airline hire the attendant?",
    "correct_answer": "f"
  },
  {
    "no": 106,
    "exp_id": "1b_2a",
    "condition": "b",
    "item_type": 3,
    "item_id": "1b_2a-3",
    "stimulus": "The pilot noticed how the pretty attendant that the famous airline hired kindly and thoughtfully gave extra attention to her daughter.",
    "target_word": "airline",
    "question": "Did the attendant give attention to a child?",
    "correct_answer": "f"
  },
  {
    "no": 107,
    "exp_id": "1b_2a",
    "condition": "c",
    "item_type": 3,
    "item_id": "1b_2a-3",
    "stimulus": "The pilot noticed that the pretty attendant that the famous airline hired kindly and thoughtfully gave extra attention to her daughter.",
    "target_word": "airline",
    "question": "Did the attendant give attention to a child?",
    "correct_answer": "f"
  },
  {
    "no": 108,
    "exp_id": "1b_2a",
    "condition": "d",
    "item_type": 3,
    "item_id": "1b_2a-3",
    "stimulus": "The pilot noticed why the pretty attendant that the famous airline hired kindly and thoughtfully gave extra attention to her daughter.",
    "target_word": "airline",
    "question": "Did the attendant give attention to a child?",
    "correct_answer": "f"
  },
  {
    "no": 109,
    "exp_id": "1b_2a",
    "condition": "a",
    "item_type": 4,
    "item_id": "1b_2a-4",
    "stimulus": "The panel remembered who the awkward scientist that the unconventional professor liked benignly and hesitantly awarded the grant to.",
    "target_word": "professor",
    "question": "Did the professor dislike the scientist?",
    "correct_answer": "j"
  },
  {
    "no": 110,
    "exp_id": "1b_2a",
    "condition": "b",
    "item_type": 4,
    "item_id": "1b_2a-4",
    "stimulus": "The panel remembered how the awkward scientist that the unconventional professor liked benignly and hesitantly awarded the grant to the researcher.",
    "target_word": "professor",
    "question": "Was a grant awarded to a researcher?",
    "correct_answer": "f"
  },
  {
    "no": 111,
    "exp_id": "1b_2a",
    "condition": "c",
    "item_type": 4,
    "item_id": "1b_2a-4",
    "stimulus": "The panel remembered that the awkward scientist that the unconventional professor liked benignly and hesitantly awarded the grant to the researcher.",
    "target_word": "professor",
    "question": "Was a grant awarded to a researcher?",
    "correct_answer": "f"
  },
  {
    "no": 112,
    "exp_id": "1b_2a",
    "condition": "d",
    "item_type": 4,
    "item_id": "1b_2a-4",
    "stimulus": "The panel remembered why the awkward scientist that the unconventional professor liked benignly and hesitantly awarded the grant to the researcher.",
    "target_word": "professor",
    "question": "Was a grant awarded to a researcher?",
    "correct_answer": "f"
  },
  {
    "no": 113,
    "exp_id": "1b_2a",
    "condition": "a",
    "item_type": 5,
    "item_id": "1b_2a-5",
    "stimulus": "The pianist remembered who the competent conductor that the beautiful cellist adored secretly and woefully sent a letter to.",
    "target_word": "cellist",
    "question": "Did the conductor send a letter to someone?",
    "correct_answer": "f"
  },
  {
    "no": 114,
    "exp_id": "1b_2a",
    "condition": "b",
    "item_type": 5,
    "item_id": "1b_2a-5",
    "stimulus": "The pianist remembered how the competent conductor that the beautiful cellist adored secretly and woefully sent a letter to the oboist.",
    "target_word": "cellist",
    "question": "Did someone send a letter to the oboist?",
    "correct_answer": "f"
  },
  {
    "no": 115,
    "exp_id": "1b_2a",
    "condition": "c",
    "item_type": 5,
    "item_id": "1b_2a-5",
    "stimulus": "The pianist remembered that the competent conductor that the beautiful cellist adored secretly and woefully sent a letter to the oboist.",
    "target_word": "cellist",
    "question": "Did someone send a letter to the oboist?",
    "correct_answer": "f"
  },
  {
    "no": 116,
    "exp_id": "1b_2a",
    "condition": "d",
    "item_type": 5,
    "item_id": "1b_2a-5",
    "stimulus": "The pianist remembered why the competent conductor that the beautiful cellist adored secretly and woefully sent a letter to the oboist.",
    "target_word": "cellist",
    "question": "Did someone send a letter to the oboist?",
    "correct_answer": "f"
  },
  {
    "no": 117,
    "exp_id": "1b_2a",
    "condition": "a",
    "item_type": 6,
    "item_id": "1b_2a-6",
    "stimulus": "The clerk remembered who the rich banker that the new manager distrusted cautiously and wrongfully cashed a check for.",
    "target_word": "manager",
    "question": "Did the banker cash a check for someone?",
    "correct_answer": "f"
  },
  {
    "no": 118,
    "exp_id": "1b_2a",
    "condition": "b",
    "item_type": 6,
    "item_id": "1b_2a-6",
    "stimulus": "The clerk remembered how the rich banker that the new manager distrusted cautiously and wrongfully cashed a check for the agent.",
    "target_word": "manager",
    "question": "Did the banker cash a check for the agent?",
    "correct_answer": "f"
  },
  {
    "no": 119,
    "exp_id": "1b_2a",
    "condition": "c",
    "item_type": 6,
    "item_id": "1b_2a-6",
    "stimulus": "The clerk remembered that the rich banker that the new manager distrusted cautiously and wrongfully cashed a check for the agent.",
    "target_word": "manager",
    "question": "Did the banker cash a check for the agent?",
    "correct_answer": "f"
  },
  {
    "no": 120,
    "exp_id": "1b_2a",
    "condition": "d",
    "item_type": 6,
    "item_id": "1b_2a-6",
    "stimulus": "The clerk remembered why the rich banker that the new manager distrusted cautiously and wrongfully cashed a check for the agent.",
    "target_word": "manager",
    "question": "Did the banker cash a check for the agent?",
    "correct_answer": "f"
  },
  {
    "no": 121,
    "exp_id": "1b_2a",
    "condition": "a",
    "item_type": 7,
    "item_id": "1b_2a-7",
    "stimulus": "The busboy revealed who the busy waitress that the talented cook hated happily and leisurely served the meal to.",
    "target_word": "cook",
    "question": "Did the waitress serve a meal to someone?",
    "correct_answer": "f"
  },
  {
    "no": 122,
    "exp_id": "1b_2a",
    "condition": "b",
    "item_type": 7,
    "item_id": "1b_2a-7",
    "stimulus": "The busboy revealed how the busy waitress that the talented cook hated happily and leisurely served the meal to the family.",
    "target_word": "cook",
    "question": "Did the waitress serve a meal to the family?",
    "correct_answer": "f"
  },
  {
    "no": 123,
    "exp_id": "1b_2a",
    "condition": "c",
    "item_type": 7,
    "item_id": "1b_2a-7",
    "stimulus": "The busboy revealed that the busy waitress that the talented cook hated happily and leisurely served the meal to the family.",
    "target_word": "cook",
    "question": "Did the waitress serve a meal to the family?",
    "correct_answer": "f"
  },
  {
    "no": 124,
    "exp_id": "1b_2a",
    "condition": "d",
    "item_type": 7,
    "item_id": "1b_2a-7",
    "stimulus": "The busboy revealed why the busy waitress that the talented cook hated happily and leisurely served the meal to the family.",
    "target_word": "cook",
    "question": "Did the waitress serve a meal to the family?",
    "correct_answer": "f"
  },
  {
    "no": 125,
    "exp_id": "1b_2a",
    "condition": "a",
    "item_type": 8,
    "item_id": "1b_2a-8",
    "stimulus": "The mailman revealed who the recent homeowner that the nosy neighbor followed suspiciously and randomly received a letter from.",
    "target_word": "neighbor",
    "question": "Did the homeowner receive a letter from someone?",
    "correct_answer": "f"
  },
  {
    "no": 126,
    "exp_id": "1b_2a",
    "condition": "b",
    "item_type": 8,
    "item_id": "1b_2a-8",
    "stimulus": "The mailman revealed how the recent homeowner that the nosy neighbor followed suspiciously and randomly received a letter from the government.",
    "target_word": "neighbor",
    "question": "Did the homeowner receive a letter from the government?",
    "correct_answer": "f"
  },
  {
    "no": 127,
    "exp_id": "1b_2a",
    "condition": "c",
    "item_type": 8,
    "item_id": "1b_2a-8",
    "stimulus": "The mailman revealed that the recent homeowner that the nosy neighbor followed suspiciously and randomly received a letter from the government.",
    "target_word": "neighbor",
    "question": "Did the homeowner receive a letter from the government?",
    "correct_answer": "f"
  },
  {
    "no": 128,
    "exp_id": "1b_2a",
    "condition": "d",
    "item_type": 8,
    "item_id": "1b_2a-8",
    "stimulus": "The mailman revealed why the recent homeowner that the nosy neighbor followed suspiciously and randomly received a letter from the government.",
    "target_word": "neighbor",
    "question": "Did the homeowner receive a letter from the government?",
    "correct_answer": "f"
  },
  {
    "no": 129,
    "exp_id": "1b_2a",
    "condition": "a",
    "item_type": 9,
    "item_id": "1b_2a-9",
    "stimulus": "The boxer revealed who the excellent trainer that the fierce competitor utilized effectively and frequently learned his trade from.",
    "target_word": "competitor",
    "question": "Did the trainer learn his trade from someoone?",
    "correct_answer": "f"
  },
  {
    "no": 130,
    "exp_id": "1b_2a",
    "condition": "b",
    "item_type": 9,
    "item_id": "1b_2a-9",
    "stimulus": "The boxer revealed how the excellent trainer that the fierce competitor utilized effectively and frequently learned his trade from his father.",
    "target_word": "competitor",
    "question": "Did the trainer learn his trade from his mother?",
    "correct_answer": "j"
  },
  {
    "no": 131,
    "exp_id": "1b_2a",
    "condition": "c",
    "item_type": 9,
    "item_id": "1b_2a-9",
    "stimulus": "The boxer revealed that the excellent trainer that the fierce competitor utilized effectively and frequently learned his trade from his father.",
    "target_word": "competitor",
    "question": "Did the trainer learn his trade from his mother?",
    "correct_answer": "j"
  },
  {
    "no": 132,
    "exp_id": "1b_2a",
    "condition": "d",
    "item_type": 9,
    "item_id": "1b_2a-9",
    "stimulus": "The boxer revealed why the excellent trainer that the fierce competitor utilized effectively and frequently learned his trade from his father.",
    "target_word": "competitor",
    "question": "Did the trainer learn his trade from his mother?",
    "correct_answer": "j"
  },
  {
    "no": 133,
    "exp_id": "1b_2a",
    "condition": "a",
    "item_type": 10,
    "item_id": "1b_2a-10",
    "stimulus": "The critic mentioned who the renowned chef that the friendly hostess liked frequently and cheerfully served the appetizer to.",
    "target_word": "hostess",
    "question": "Did the chef serve dessert to someone?",
    "correct_answer": "j"
  },
  {
    "no": 134,
    "exp_id": "1b_2a",
    "condition": "b",
    "item_type": 10,
    "item_id": "1b_2a-10",
    "stimulus": "The critic mentioned how the renowned chef that the friendly hostess liked frequently and cheerfully served the appetizer to the patron.",
    "target_word": "hostess",
    "question": "Did the chef serve a dessert to a patron?",
    "correct_answer": "j"
  },
  {
    "no": 135,
    "exp_id": "1b_2a",
    "condition": "c",
    "item_type": 10,
    "item_id": "1b_2a-10",
    "stimulus": "The critic mentioned that the renowned chef that the friendly hostess liked frequently and cheerfully served the appetizer to the patron.",
    "target_word": "hostess",
    "question": "Did the chef serve a dessert to a patron?",
    "correct_answer": "j"
  },
  {
    "no": 136,
    "exp_id": "1b_2a",
    "condition": "d",
    "item_type": 10,
    "item_id": "1b_2a-10",
    "stimulus": "The critic mentioned why the renowned chef that the friendly hostess liked frequently and cheerfully served the appetizer to the patron.",
    "target_word": "hostess",
    "question": "Did the chef serve a dessert to a patron?",
    "correct_answer": "j"
  },
  {
    "no": 137,
    "exp_id": "1b_2a",
    "condition": "a",
    "item_type": 11,
    "item_id": "1b_2a-11",
    "stimulus": "The assistant mentioned who the lovely bride that the skilled tailor intimidated purposefully and obviously sold the dress to.",
    "target_word": "tailor",
    "question": "Did the bride borrow her dress from someone?",
    "correct_answer": "j"
  },
  {
    "no": 138,
    "exp_id": "1b_2a",
    "condition": "b",
    "item_type": 11,
    "item_id": "1b_2a-11",
    "stimulus": "The assistant mentioned how the lovely bride that the skilled tailor intimidated purposefully and obviously sold the dress to a celebrity.",
    "target_word": "tailor",
    "question": "Did the bride sell the dress to a celebrity?",
    "correct_answer": "f"
  },
  {
    "no": 139,
    "exp_id": "1b_2a",
    "condition": "c",
    "item_type": 11,
    "item_id": "1b_2a-11",
    "stimulus": "The assistant mentioned that the lovely bride that the skilled tailor intimidated purposefully and obviously sold the dress to a celebrity.",
    "target_word": "tailor",
    "question": "Did the bride sell the dress to a celebrity?",
    "correct_answer": "f"
  },
  {
    "no": 140,
    "exp_id": "1b_2a",
    "condition": "d",
    "item_type": 11,
    "item_id": "1b_2a-11",
    "stimulus": "The assistant mentioned why the lovely bride that the skilled tailor intimidated purposefully and obviously sold the dress to a celebrity.",
    "target_word": "tailor",
    "question": "Did the bride sell the dress to a celebrity?",
    "correct_answer": "f"
  },
  {
    "no": 141,
    "exp_id": "1b_2a",
    "condition": "a",
    "item_type": 12,
    "item_id": "1b_2a-12",
    "stimulus": "The baker mentioned who the young mother that the sweet child hugged hurriedly and frantically bought the cake for.",
    "target_word": "child",
    "question": "Did the mother buy a cake?",
    "correct_answer": "f"
  },
  {
    "no": 142,
    "exp_id": "1b_2a",
    "condition": "b",
    "item_type": 12,
    "item_id": "1b_2a-12",
    "stimulus": "The baker mentioned how the young mother that the sweet child hugged hurriedly and frantically bought the cake for her sister.",
    "target_word": "child",
    "question": "Did the mother buy a cake for her sister?",
    "correct_answer": "f"
  },
  {
    "no": 143,
    "exp_id": "1b_2a",
    "condition": "c",
    "item_type": 12,
    "item_id": "1b_2a-12",
    "stimulus": "The baker mentioned that the young mother that the sweet child hugged hurriedly and frantically bought the cake for her sister.",
    "target_word": "child",
    "question": "Did the mother buy a cake for her sister?",
    "correct_answer": "f"
  },
  {
    "no": 144,
    "exp_id": "1b_2a",
    "condition": "d",
    "item_type": 12,
    "item_id": "1b_2a-12",
    "stimulus": "The baker mentioned why the young mother that the sweet child hugged hurriedly and frantically bought the cake for her sister.",
    "target_word": "child",
    "question": "Did the mother buy a cake for her sister?",
    "correct_answer": "f"
  },
  {
    "no": 145,
    "exp_id": "1b_2a",
    "condition": "a",
    "item_type": 13,
    "item_id": "1b_2a-13",
    "stimulus": "The surgeon disclosed who the ambitious nurse that the old doctor recommended unfairly and ignorantly promised the cure to.",
    "target_word": "doctor",
    "question": "Did the doctor recommend the nurse?",
    "correct_answer": "f"
  },
  {
    "no": 146,
    "exp_id": "1b_2a",
    "condition": "b",
    "item_type": 13,
    "item_id": "1b_2a-13",
    "stimulus": "The surgeon disclosed how the ambitious nurse that the old doctor recommended unfairly and ignorantly promised the cure to the patient.",
    "target_word": "doctor",
    "question": "Did the nurse promise a cure to the patient?",
    "correct_answer": "f"
  },
  {
    "no": 147,
    "exp_id": "1b_2a",
    "condition": "c",
    "item_type": 13,
    "item_id": "1b_2a-13",
    "stimulus": "The surgeon disclosed that the ambitious nurse that the old doctor recommended unfairly and ignorantly promised the cure to the patient.",
    "target_word": "doctor",
    "question": "Did the nurse promise a cure to the patient?",
    "correct_answer": "f"
  },
  {
    "no": 148,
    "exp_id": "1b_2a",
    "condition": "d",
    "item_type": 13,
    "item_id": "1b_2a-13",
    "stimulus": "The surgeon disclosed why the ambitious nurse that the old doctor recommended unfairly and ignorantly promised the cure to the patient.",
    "target_word": "doctor",
    "question": "Did the nurse promise a cure to the patient?",
    "correct_answer": "f"
  },
  {
    "no": 149,
    "exp_id": "1b_2a",
    "condition": "a",
    "item_type": 14,
    "item_id": "1b_2a-14",
    "stimulus": "The farmer disclosed who the passionate rancher that the boring businessman judged unnecessarily and intensely studied in college with.",
    "target_word": "businessman",
    "question": "Did the businessman judge the rancher?",
    "correct_answer": "f"
  },
  {
    "no": 150,
    "exp_id": "1b_2a",
    "condition": "b",
    "item_type": 14,
    "item_id": "1b_2a-14",
    "stimulus": "The farmer disclosed how the passionate rancher that the boring businessman judged unnecessarily and intensely studied in college with the professors.",
    "target_word": "businessman",
    "question": "Did the rancher study in college?",
    "correct_answer": "f"
  },
  {
    "no": 151,
    "exp_id": "1b_2a",
    "condition": "c",
    "item_type": 14,
    "item_id": "1b_2a-14",
    "stimulus": "The farmer disclosed that the passionate rancher that the boring businessman judged unnecessarily and intensely studied in college with the professors.",
    "target_word": "businessman",
    "question": "Did the rancher study in college?",
    "correct_answer": "f"
  },
  {
    "no": 152,
    "exp_id": "1b_2a",
    "condition": "d",
    "item_type": 14,
    "item_id": "1b_2a-14",
    "stimulus": "The farmer disclosed why the passionate rancher that the boring businessman judged unnecessarily and intensely studied in college with the professors.",
    "target_word": "businessman",
    "question": "Did the rancher study in college?",
    "correct_answer": "f"
  }
]